version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - VECTOR_STORE_PATH=/app/vector_store
    volumes:
      - ./vector_store:/app/vector_store
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # maps nginx:80 to host:3000 for convenience
    depends_on:
      - backend
    restart: unless-stopped

# Optional named volume (not required since we mount host folder)
volumes:
  vector_store:
    driver: local
